# Generated by Django 4.2.11 on 2024-07-21 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('tracking_number', models.CharField(max_length=50)),
                ('origin_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('courier_selected', models.CharField(blank=True, max_length=50, null=True)),
                ('status_milestone', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('couriers_involved', models.ManyToManyField(blank=True, related_name='participants', to='base.courier')),
                ('delivery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.deliverytype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('modification', models.TextField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
            },
        ),
        migrations.CreateModel(
            name='TrackingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_tracking_number', models.CharField(max_length=50, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('occurrence_date_time', models.DateTimeField(null=True)),
                ('status_milestone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.courier')),
                ('tracking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trackingnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_received_date_time', models.DateTimeField(blank=True, null=True)),
                ('in_transit_date_time', models.DateTimeField(blank=True, null=True)),
                ('outFor_delivery_date_time', models.DateTimeField(blank=True, null=True)),
                ('failed_attempt_date_time', models.DateTimeField(blank=True, null=True)),
                ('available_for_pickup_date_time', models.DateTimeField(blank=True, null=True)),
                ('exception_date_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_date_time', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trackingnumber')),
            ],
        ),
    ]
